# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='likedUsers',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_items', to='first_app.User'),
        ),
    ]
