# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180422_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
